config/routes.rb
Rails.application.routes.draw do
  get 'charts/chartview'
  get 'chart/chartview'
  get 'home/chartview'
  devise_for :users
  root to: 'pages#home'
  resources :expenses #Matan testing purposes, delete later

  resource :profile, only: [:show]

  resources :accounts, only: [:create] do
    resources :expenses, only: [:create]
  end

  resources :recommendations, only: [:index, :show] do
    resources :pledges, only: [:create]
  end

  resources :pledges, only: [:index] do
    member do
      patch :complete
    end
  end


  resource :dashboard, only: [:show]

  get "/calculate", to: "expenses#set_transactions", as: "fetch_expenses"

  resource :chart, only: [:chartview]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    get '/kitchensink', to: 'pages#kitchensink'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.new(pledge_params)
  end

  def delete
  end

  def show
    @pledges = Pledge.all
    @completed_pledges = Pledge.where(completed: true)
    @total_co2_achieved = @completed_pledges.map{|pledge| pledge.recommendation.co2_grams}.sum
  end
end

app/views/profiles/_accordion_profiles.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
      <div class="card-header" id="headingOne">
        <p class="mb-0">
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse-<%= pledge.id %>" aria-expanded="true" aria-controls="collapseOne">
              <p><strong><%= pledge.recommendation.title %></strong> = <%= pledge.recommendation.co2_grams %> CO2 grams</p>
          </button>
        </p>
      </div>

      <div id="collapse-<%= pledge.id %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
            <%= pledge.recommendation.description %>
            <br>
            <%= link_to "Link to article", pledge.recommendation.link_to_article %>
        </div>
      </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div>
  <span class="typed d-flex justify-content-center " id="banner-typed-text"></span>
</div>
<br><br>
  <h1 class="your-pledges d-flex justify-content-center position-">Your latest pledges</h1>
  <div class="seedling-container">
    <button class="seedling-button"><i id="seedling" class="fas fa-seedling"></i><%= link_to " Pledges", pledges_path  %></button>
  </div>
<div class="container-all-pledges">
    <div class="card-container">
        <% @pledges.last(3).each do |pledge| %>
            <% if pledge.completed == false %>
            <%= render "accordion_profiles", pledge: pledge %>
            <% unless pledge.completed %>
            <%= link_to "complete", complete_pledge_path(pledge), method: :patch %>
            <% end %>
            <% end %>
        <% end %>
    </div>
</div>
<h1 class="comp-pledges d-flex justify-content-center">Latest completed pledges</h1>
<p class="total-co2 d-flex justify-content-center">You've helped reduce <%= @total_co2_achieved %> kg of CO2!</p>
<div class="container-all-pledges">
  <div class="card-container">
    <% @completed_pledges.first(3).each do |pledge| %>
        <% pledge.completed %>
        <%= render "accordion_profiles", pledge: pledge %>
        <% unless pledge.completed %>
        <%= link_to "complete", complete_pledge_path(pledge), method: :patch %>
      <% end %>
    <% end %>
   </div>
</div>