config/routes.rb
Rails.application.routes.draw do
  get 'charts/chartview'
  get 'chart/chartview'
  get 'home/chartview'
  devise_for :users
  root to: 'pages#home'
  resources :expenses #Matan testing purposes, delete later

  resource :profile, only: [:show]

  resources :accounts, only: [:create] do
    resources :expenses, only: [:create]
  end

  resources :recommendations, only: [:index, :show] do
    resources :pledges, only: [:create]
  end

  resources :pledges, only: [:index] do
    member do
      patch :complete
    end
  end


  resource :dashboard, only: [:show]

  get "/calculate", to: "expenses#set_transactions", as: "fetch_expenses"

  resource :chart, only: [:chartview]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    get '/kitchensink', to: 'pages#kitchensink'
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_many :impacts
  has_many :pledges
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recommendations = Recommendation.all
    @reco_selected = true
  end

  def show
    @recommendation = Recommendation.find(params[:id])
    @reco_selected = true
  end
end

app/views/recommendations/_accordion_recommendations.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
      <div class="card-header" id="headingOne">
        <p class="mb-0">
          <button style="text-decoration:none; color: black" class="btn btn-link btn-block text-left reco-show-btn-container" type="button" data-toggle="collapse" data-target="#collapse-<%= recommendation.id %>" aria-expanded="true" aria-controls="collapseOne">
              <%= "#{recommendation.title} = #{recommendation.co2_grams/1000} CO2 KGs" %>
              <p>Read more: <i class="fas fa-chevron-down"></i></p>
          </button>
        </p>
      </div>

      <div id="collapse-<%= recommendation.id %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
            <p><%= recommendation.description %></p>
            <br>
            <p><i class="fas fa-link"></i> <%= link_to "Link to article", recommendation.link_to_article %></p>
        </div>
      </div>
  </div>
</div>

app/views/recommendations/index.html.erb
<% content_for :meta_title, "Eco-Logical | Recommendations, let us help you" %>
<% content_for :meta_description, "Find out how you can change your current behavior in order to achieve your ecological ambitions." %>
<% content_for :meta_image, image_path("cover.png") %>

<h3 style="text-align:center;" class="dashboard-banner py-5">Offset Actions</h3>
<br>
<h3 class="offset-recommendations-subheader">Swipe to go <strong>green -></strong></h3>


<div id="mySwipe" class="swipe">
  <div class="swipe-wrap"> <!--start of swipe-wrap-->
    <% @recommendations.each do |recommendation| %>
      <div class="swipe-container">
          <div style="background-image: url(<%= recommendation.photo %>);" class="swipe-image-index">
          <strong><h5 class="reco-index-title"><%= recommendation.category %></h5></strong>
            <div>
              <p class="swipe-title-container"><strong class=""><%= recommendation.title %></strong></p>
            </div>
              <div class="swipe-grams-container">
                  <p class="space-words"><%= "Offset:" %></p>
                  <p class="counterUp space-words" akhi=<%= recommendation.co2_grams/1000 %>>0</p>
                  <p class="space-words"><%= " CO2 KGs" %></p>
              </div>
              <div class="swipe-btn-container">
                <%= link_to "More Info", recommendation_path(recommendation.id), class:"button-know-more" %>
                <%= simple_form_for([recommendation, Pledge.new]) do |f| %>
                  <%= f.submit %>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div> <!--end of swipe-wrap-->
</div> <!--end of div-->

app/views/recommendations/show.html.erb
<% content_for :meta_title, "Eco-Logical | Recommendations, let us help you" %>
<% content_for :meta_description, "Find out how you can change your current behavior in order to achieve your ecological ambitions." %>
<% content_for :meta_image, image_path("cover.png") %>


<div class="accordion-container">
  <h3 style="text-align:center;" class="dashboard-banner py-5"><%= "How to offset: #{@recommendation.category}" %></h3>
  <div style="background-image: url(<%= @recommendation.photo %>);" class="swipe-image"></div>
  <%= render "accordion_recommendations", recommendation: @recommendation %>
  <div class = "swipe-btn-show-container">
    <%= link_to "Back to Actions", recommendations_path, class:"button-know-more" %>
    <%= simple_form_for([@recommendation, Pledge.new]) do |f| %>
      <%= f.submit %>
    <% end %>
  </div>
</div>