config/routes.rb
Rails.application.routes.draw do
  get 'charts/chartview'
  get 'chart/chartview'
  get 'home/chartview'
  devise_for :users
  root to: 'pages#home'
  resources :expenses #Matan testing purposes, delete later

  resource :profile, only: [:show]

  resources :accounts, only: [:create] do
    resources :expenses, only: [:create]
  end

  resources :recommendations, only: [:index, :show] do
    resources :pledges, only: [:create]
  end

  resources :pledges, only: [:index] do
    member do
      patch :complete
    end
  end


  resource :dashboard, only: [:show]

  get "/calculate", to: "expenses#set_transactions", as: "fetch_expenses"

  resource :chart, only: [:chartview]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    get '/kitchensink', to: 'pages#kitchensink'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div  class="  navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to recommendations_path, class: "navbar-brand" do %>
       <i class="fas fa-seedling"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>
  <%= link_to dashboard_path, class: "navbar-brand" do %>
    <i class="fas fa-chart-pie"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>
  <%= link_to pledges_path, class: "navbar-brand" do %>
    <%#= image_tag "app/assets/images/logo.png" %>
      <i class="fas fa-user"></i>
      <span class="pledge-count23"><%= Pledge.all.where(completed:false).count%></span>
    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

</div>

app/views/shared/_navbardash.html.erb
<div  class="  navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to recommendations_path, class: "navbar-brand" do %>
       <i class="fas fa-seedling"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

  <%= link_to dashboard_path, class: "navbar-brand" do %>
    <i class="fas fa-chart-pie navbar-icon-green"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

  <%= link_to pledges_path, class: "navbar-brand" do %>
    <div navbar-icon-counter>
      <i class="fas fa-user"></i>
      <span class="pledge-count23"><%= Pledge.all.where(completed:false).count%></span>
    </div>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

</div>

app/views/shared/_navbarpledge.html.erb
<div  class="  navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to recommendations_path, class: "navbar-brand" do %>
    <i class="fas fa-seedling"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

  <%= link_to dashboard_path, class: "navbar-brand" do %>
    <i class="fas fa-chart-pie"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>
  <div>
  <%= link_to pledges_path, class: "navbar-brand" do %>
      <i class="fas fa-user navbar-icon-green"></i>
      <span class="pledge-count23"><%= Pledge.all.where(completed:false).count%></span>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>
  </div>
</div>

app/views/shared/_navbarreco.html.erb
<div  class="  navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to recommendations_path, class: "navbar-brand" do %>
  <i class="fas fa-seedling navbar-icon-green"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

  <%= link_to dashboard_path, class: "navbar-brand" do %>
    <i class="fas fa-chart-pie"></i>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

  <%= link_to pledges_path, class: "navbar-brand" do %>
    <i class="fas fa-user"></i>
    <span class="pledge-count23"><%= Pledge.all.where(completed:false).count%></span>
    <%#= image_tag "app/assets/images/logo.png" %>

    <%#= cl_image_tag "qflbyl0yz7z8cw4wwnej" %>
  <% end %>

</div>