config/routes.rb
Rails.application.routes.draw do
  get 'charts/chartview'
  get 'chart/chartview'
  get 'home/chartview'
  devise_for :users
  root to: 'pages#home'
  resources :expenses #Matan testing purposes, delete later

  resource :profile, only: [:show]

  resources :accounts, only: [:create] do
    resources :expenses, only: [:create]
  end

  resources :recommendations, only: [:index, :show] do
    resources :pledges, only: [:create]
  end

  resources :pledges, only: [:index] do
    member do
      patch :complete
    end
  end


  resource :dashboard, only: [:show]

  get "/calculate", to: "expenses#set_transactions", as: "fetch_expenses"

  resource :chart, only: [:chartview]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    get '/kitchensink', to: 'pages#kitchensink'
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @counter = 1
    @expense = Expense.new
    @accounts = current_user.accounts
    params[:scope].present? ? @time = params[:scope].to_i : @time = "all"
    @categories = current_user.unique_category
    @expenses_chart = Expense.populate_chart(@time)
    @total_expenses = user_total_expenses(@time)
    @total_emmissions = user_total_emmissions(@time)
    @emmissions = current_user.emmissions.date_filtered_emmissions(@time, current_user)
    @emmission_chart = Emmission.populate_chart(@time)
    respond_to do |format|
      format.html
      format.text { render partial: 'dashboards/dashboard_info', locals: {}, formats: [:html] }
      @dash_selected = true
    end
  end

  def user_total_expenses(time)
    case time
    when "all"
      current_user.user_total_expenses
    else
      current_user.expenses.date_filter(time).collect(&:amount).sum(&:to_f)
    end
  end

  def user_total_emmissions(time)
    total = 0
    case time
    when "all"
      return (current_user.user_total_emmissions.to_f * current_user.user_total_expenses.to_f) / 1000
    else
      current_user.expenses.date_filter(time).each do |expense|
        total += expense.emmission.co2_grams unless expense.emmission.co2_grams.nil?
      end
    end
    return total
  end
end

app/views/dashboards/_accordion.html.erb
<div>
  <div class="" id="headingOne">
    <h2 class="mb-0">
      <button type="button" class="text-card-dash btn btn-link btn-block text-left" data-toggle="modal" data-target="#Modal-<%= cat.split.first %>">
          <h2 class="card-header-dash"><strong><%= cat %></strong></h2>
      </button>
    </h2>
      <div class="d-flex dprop">
        <div class="greendash1money">
          <i class="fas fa-money-bill-wave "></i>
          <% money = current_user.total_expenses_per_category([cat, time]) %>
          <p class="title"><%= money.round() %> EUR</p>
        </div>
        <div class="greendash1" data-update-list-target="card<%= @counter %>"
             data-action="click->update-list#flip">
          <% final_calc = (current_user.total_emmissions_per_category(cat).to_f * current_user.total_expenses_per_category([cat, time]).to_f) / 1000 %>
          <i class="fas fa-burn white-icon"></i>
          <% if final_calc > 1000 %>
            <% final_calc /= 1000 %>
            <div class="d-flex mp1234" >
              <p class="title"><%= final_calc.round() %>  </p>
              <p class="card-info title">Tco2</p>
            </div>
          <% else %>
          <div class="d-flex mp1234">
            <p class="whole title"><%= final_calc.round() %></p>
            <p class="card-info title"> CO2 Kg</p>
          </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/dashboards/_dashboard_info.html.erb
  <div data-controller="update-list">
   <div data-update-list-target="description">
    <div class="text-center dashboard-banner">
      <h3><%= link_to "Welcome", "/"%> <%= current_user.first_name %></h3>
      <p> <%= current_user.unique_account[0] %></p>
      <%= link_to fetch_expenses_path do %>
        <i class="fas fa-cloud-download-alt"></i>
      <% end %>
    </div>
    <div class="dashboard-h2">
      <div>
          <div class="info-container">
            <div class="d-flex info-block">
              <i class="fas fa-money-bill-wave icon1"></i>
              <p class="title text-green"><%= @total_expenses.ceil(2) %> EUR </p>
              <p class="title">Expenses </p>
            </div>
              <div class="d-flex info-block">
                <i class="fas fa-burn icon2"></i>
                <p class="title text-green"><%= ((@total_emmissions)/10000).ceil(2) %> TCO2</p>
                <p class="title">Emmissions </p>
              </div>
              <div class="d-flex info-block">
                <i class="fas fa-leaf"></i>
                <p class="title text-green"><%= (current_user.pledge_impact)/1000000 %> TCO2</p>
                <p class="title">Offset </p>
              </div>
              <div class="d-flex info-block">
              <i class="fas fa-globe-europe"></i>
              <% calc_net = (@total_emmissions/10000) - (current_user.pledge_impact/1000000) %>
              <p class="title text-green"> <%= calc_net.ceil(2) %> TCO2</p>
              <p class="title">Net Emmissions</p>
              </div>
            </div>
          </div>

      <div>
        <div class=" d-flex hb32 months-dash ">
          <%= link_to "30 Days", dashboard_path(scope: 1), id: "month", class: "title-filter", "data-action": "click->update-list#filter" %>
          <%= link_to "3 Months", dashboard_path(scope: 3), id: "three", class: "title-filter", "data-action": "click->update-list#filter" %>
          <%= link_to "6 Months", dashboard_path(scope: 6), id: "six", class: "title-filter", "data-action": "click->update-list#filter"%>
        </div>
      </div>
      <div class="container" data-update-list-target="charts">
        <div class="chart" style="text-align: center">
          <div class="show1" id="chartOne">
            <h5 class="header-chart title">CO2 KGs</h5>
            <%= pie_chart @emmission_chart, donut: true, legend: "left", colors: ["#3cdc8c", "#93ecbf", "#e9fbf2", "#1b9759", "#0c4126", "#bef3d9"] %>
          </div>
          <div class="hide1" id="chartTwo">
            <h5 class="header-chart1 title"> Expenses €</h5>
            <%= pie_chart @expenses_chart, donut: true, legend: "right", colors: ["#3cdc8c", "#93ecbf", "#e9fbf2", "#1b9759", "#0c4126", "#bef3d9"] %>
          </div>
          <p id="btn" class=""><i class="green-me-up-btn-dash title">Change View</i></p>
        </div>
      </div>
    </div>
    <div class="container ">
      <br>
        <a href="/expenses/new" class="float">
          <i class="fa fa-plus my-float"></i>
        </a>
      <% @categories.each do |cat| %>
        <div class="dashboard-h3 ">
          <%= render "accordion", cat: cat, time: @time %>
        </div>
        <%= render "modals", cat: cat%>
        <% @counter += 1 %>
      <% end %>
      <p>-----------------------</p>
      <br>
    </div>
   </div>
</div>

app/views/dashboards/_modals.html.erb
<div class=" modal fade" id="Modal-<%= cat.split.first %>" tabindex="-1" role="dialog"
  aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="  modal-dialog" role="document">
    <div class=" modal13 modal-content">
      <div class="modal-header">
        <strong>
          <h4 class="dashboardModalBreakdown title text-green" style="font-size:  1.2rem"><%= "Breakdown of #{cat}" %></h4>
        </strong>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @emmissions.where(sub_category: cat).each do |emmission| %>
        <div class="modal-container">
         <div class="d-flex info-block">
           <h5 class="title text-green"><%= emmission.expense.creditor_name %></h5>
         </div>
         <div class="d-flex info-block">
          <i class="fas fa-calendar-alt"></i>
          <p><%= emmission.expense.date %></p>
         </div>
         <div class="d-flex info-block">
          <i class="fas fa-money-bill-wave"></i>
          <p><%= emmission.expense.amount %> EUR</p>
         </div>
         <div class="d-flex info-block">
          <% calc_result =  (emmission.co2_grams.to_f * emmission.expense.amount.to_f) / 1000 %>
          <i class="fas fa-fire"></i>
          <p><%= calc_result.ceil(2) %> Kg CO2</p>
         </div>
          <p class="modal-bottom-line"></p>
        </div>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-dash" style="width: 100%;" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<% content_for :meta_title, "Eco-Logical | Dashboard" %>
<% content_for :meta_description, "Real-time data on your expenses and your emmissions. Get to know your real impact, so that you can achieve your ecological ambitions." %>
<% content_for :meta_image, image_path("cover.png") %>


<%= render "dashboard_info" %>